#+TITLE: RSS Feed For Youtube
#+AUTHOR: Leonardo Tamiano

* What is RSS?

  #+begin_example
RSS is a Web content syndication format.

Its name is an acronym for Really Simple Syndication.

RSS is a dialect of XML. All RSS files must conform to the XML 1.0 specification, as published on the World Wide Web Consortium (W3C) website.
  #+end_example
 
  Taken from
  https://cyber.harvard.edu/rss/rss.html

  ---------------

  The idea behind RSS is simple:

  1. Use an RSS client and subscribe to an RSS feed
     
  2. When new content is created, the RSS feed is updated
     
  3. The RSS clients regularly fetch the RSS feed, and in case of
     updates they signal the final user of the new content
  
* Introducing a new RSS feed
  You can now subscribe to the following feed for updates regarding my youtube channel.

  https://leonardotamiano.xyz/rss/yt-en.xml

  You can also checkout directly from the github repository of the channel

  https://github.com/LeonardoE95/yt-en/blob/main/feed/rss.xml

  In order to use it I suggest the following applications:

  - Emacs RSS client: https://github.com/skeeto/elfeed    
  - RSS reader for iOS: https://netnewswire.com/

* How do I generate it?
  If you're interested in how I generate the feed, you can checkout my blog

  https://blog.leonardotamiano.xyz/tech/rss-feed-emacs-lisp/

  The basic idea is that I use ~emacs-lisp~ for automatically
  generating the feed based on an ~org-mode~ file containing useful
  metadata for each video.

  #+begin_example
youtube.org --> emacs-lisp --> RSS feed
  #+end_example


